[tools]
"aqua:apache/maven" = "latest"
"aqua:ast-grep/ast-grep" = "latest"
"aqua:gradle/gradle" = "latest"
"npm:corepack" = "latest"
"npm:npm-check-updates" = "latest"
"npm:prettier" = "latest"
"ubi:google/google-java-format" = "latest"
bun = "latest"
go = "latest"
node = "latest"
usage = "latest"
uv = "latest"
"ubi:reteps/dockerfmt" = "latest"
biome = "latest"
java = "latest"

[settings]
idiomatic_version_file_enable_tools = ["java"]
